// // import { useUser } from "@auth0/nextjs-auth0/client";
// // import { useSession } from '@auth0/nextjs-auth0';
// // import {signIn} from "next-auth/react";
// import { signIn, signOut, getSession, useSession } from "next-auth/react";
// import Head from "next/head";

// const Login = () => {


//   const { data: session, status } = useSession({ required: true });

//   // async function fetchSession() {
//   //   const session = await getSession(context);
//   //   console.log("GET THE SESSION!!!", session);
//   // }
//   // const { user, error, isLoading } = useUser();
//   // const [session, loading] = getSession();

//   // Check if the user is authenticated
//   // const isAuthenticated = session && session.user;

//   // Access the access token from the session if authenticated
//   // const accessToken = isAuthenticated ? session.accessToken : null;


//   // console.log('Access TokenAUTH000000000000!!!!!!!!:', accessToken);


//   // useEffect(() => {
//   //   // Check if the session is available and not loading
//   //   if (session && !loading) {
//   //     // Access the access token from the session
//   //     const accessToken = session.accessToken;

//   //     // Log the access token
//   //     
//   //   }
//   // }, [session, loading]);

//   // useEffect(() => {
//   //   console.log("accessToken:", session.accessToken);
//   // }, []);


//   const logoUrl = `/images/logo.jpg`;

//   // if (isLoading) return <div>Loading...</div>;
//   // if (error) return <div>{error.message}</div>;
//   // if (user){
//   //   return (
//   //     user && (
//   //         <div>
//   //           <img src={user.picture} alt={user.name} />
//   //           <h2>{user.name}</h2>
//   //           <p>{user.email}</p>
//   //           <a href="/api/auth/logout" className="mt-2 text-blue-500 hover:underline">
//   //           Log out
//   //         </a>
//   //         </div>
//   //     )
//   // );

//   // }

//   // fetchSession()
  
//   return (
//     <>

// <div >
//   <Head>
//          <title>Next Auth0 demo</title>
//          <meta name="description" content="Generated by create next app" />
//          <link rel="icon" href="/favicon.ico" />
//        </Head>

//        {session ? (
//         <button onClick={() => signOut()}>Sign out</button>
//       ) : (
//         <button onClick={() => signIn()}>Sign in</button>
//       )}
//       {session && (
//         <div>
//           <p>Signed in as {session.user.email}</p>
//           <p>Name {session.user.name}</p>
//           {/* <Image
//             width={200}
//             height={200}
//             src={session.user.image}
//             alt={session.user.name}
//           /> */}
//         </div>
//       )}
//     </div>

//       {/* <section className="bg-gray-50 dark:bg-gray-900">
//   <div className="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
//     <div className="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
//       <div className="p-6 space-y-4 md:space-y-6 sm:p-8">
//         <div className="flex flex-col items-center justify-center mb-4">
//           <img src={logoUrl} alt="Logo" /> */}
//           {/* <a href="/api/auth/signin" className="mt-2 text-blue-500 hover:underline"
//           onClick={(e) => {
//             e.preventDefault();
//             signIn("auth0");
//         }}>
//             Log in
//           </a> */}
         
//         {/* </div> */}
// {/* 
//         {session ? (
//         <button onClick={() => signOut()}>Sign out</button>
//       ) : (
//         <button onClick={() => signIn()}>Sign in</button>
//       )} */}
//       {/* </div>
//     </div>
//   </div>
// </section> */}

//     </>
//   );
// };

// export default Login;


import Head from "next/head";

import { getSession, signIn, signOut, useSession } from "next-auth/react";
import {useEffect} from "react";
import {useRouter} from "next/router";

export default function Login({ session }) {

  const router = useRouter();

  const { status } = useSession();
    useEffect  (() => {
        if (status === "authenticated") {
            void router.push("/apps");
        }
    }, [status]);

  return (
    <div >
      <Head>
        <title>Next Auth0 demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {session ? (
        <button onClick={() => signOut()}>Sign out</button>
      ) : (
        <button onClick={() => signIn()}>Sign in</button>
      )}
      {session && (
        <div>
          <p>Signed in as {session.user.email}</p>
          <p>Name {session.user.name}</p>

        </div>
      )}
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const session = await getSession(context);

  console.log("THIS IS THE SESSION LOGIN!!!!!!",session)

  return {
    props: {
      session,
    },
  };
};